[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

remappings = [
  'forge-std/=lib/forge-std/src/',
  'foundry-devops/=lib/foundry-devops/src/',
  '@chainlink/contracts/=lib/chainlink/contracts/',
  '@chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/contracts/'
]
ffi = true
